### ISSUE TITLE
Revoke/Remove Ray's keys

### ISSUE THREAD

**Issue by lazka** [msys2/MSYS2-keyring#9]

**Comment by Biswa96** [comment]
Is there any way to know if a package was signed by him?

**Comment by jeremyd2019** [comment]
1. signer info is on packages.msys2.org, but that would only tell you about *current* packages I think
2. a script could be made pretty straightforwardly I think to look at all .sig files for his key id

**Comment by lazka** [comment]
good point, would be good to know first

**Comment by lazka** [comment]
signatures of all `*.sig` files

* 8801 signatures: https://keyserver.ubuntu.com/pks/lookup?search=0x5F92EFC1A47D45A1&fingerprint=on&op=index
* 9530 signatures: https://keyserver.ubuntu.com/pks/lookup?search=0xFA11531AA0AA7F57&fingerprint=on&op=index
* 6519 signatures: https://keyserver.ubuntu.com/pks/lookup?search=0x628F528CF3053E04&fingerprint=on&op=index

so all good

**Comment by elieux** [comment]
Let's do it?

**Comment by elieux** [comment]
We have to deal with the master key as well.
